services:
  - type: web
    name: autoscraper
    runtime: docker
    plan: free
    envVars:
      - key: LIVE_SCRAPE_ENABLED
        value: "true"
      - key: SECRET_KEY
        generateValue: true
